In [1]:
import pandas as pd

In [2]:
url='https://es.wikipedia.org/wiki/Pandemia_de_enfermedad_por_coronavirus_de_2020_en_Per%C3%BA#Marzo'
df_list=pd.read_html(url)

In [3]:
len(df_list)

10

In [8]:
t=df_list[8]
t.to_csv("tabla.csv",index=False)

In [12]:
ch=pd.read_csv("tabla.csv")
#ch=ch.drop([0,2], axis=0)
#t=ch.iloc[:,[0,27]] #iloc[:, [0,2,1]] 
#t #tabla
ch

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Semana,Fecha,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,NaN,Pruebas,Pruebas
1,Semana,Fecha,Activos,Activos,Confirmados,Confirmados,Recuperados,Recuperados,Fallecidos,Fallecidos,NaN,Severos,Severos,NaN,PCR+PR,PCR+PR
2,Semana,Fecha,Var.,Acum.,Nuevos,Acum.,Nuevos,Acum.,Nuevos,Acum.,NaN,Hosp.,UCI,NaN,Nuevos,Acum.
3,Sem. 1,6-3-2020,1,1,1,1,-,-,-,-,NaN,-,-,NaN,155,155
4,Sem. 1,7-3-2020,5,6,5,6,-,-,-,-,NaN,-,-,NaN,64,219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,Sem. 35,25-10-2020,-1343,46 930,2501,888 715,3790,807 636,54,34 149,NaN,5492,1050,NaN,22 433,4 390 402
251,Sem. 35,26-10-2020,-1548,46 930,1859,890 574,3359,810 995,48,34 197,NaN,5615,1070,NaN,16 891,4 407 293
252,Semana,Fecha,Var.,Acum.,Nuevos,Acum.,Nuevos,Acum.,Nuevos,Acum.,NaN,Hosp.,UCI,NaN,Nuevos,Acum.
253,Semana,Fecha,Activos,Activos,Confirmados,Confirmados,Recuperados,Recuperados,Muertes,Muertes,NaN,Severos,Severos,NaN,PCR+PR,PCR+PR
254,Semana,Fecha,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,NaN,Pruebas,Pruebas

In [9]:
a=t.iloc[200:206]
a.to_csv("tmp.csv")

In [ ]:
xls=pd.read_excel('coronavirus.xlsx') #,sheet_name=""
xls.iloc[199]

In [7]:
df_list[8]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Semana,Fecha,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,NaN,Pruebas,Pruebas
1,Semana,Fecha,Activos,Activos,Confirmados,Confirmados,Recuperados,Recuperados,Fallecidos,Fallecidos,NaN,Severos,Severos,NaN,PCR+PR,PCR+PR
2,Semana,Fecha,Var.,Acum.,Nuevos,Acum.,Nuevos,Acum.,Nuevos,Acum.,NaN,Hosp.,UCI,NaN,Nuevos,Acum.
3,Sem. 1,6-3-2020,1,1,1,1,-,-,-,-,NaN,-,-,NaN,155,155
4,Sem. 1,7-3-2020,5,6,5,6,-,-,-,-,NaN,-,-,NaN,64,219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,Sem. 35,25-10-2020,-1343,46 930,2501,888 715,3790,807 636,54,34 149,NaN,5492,1050,NaN,22 433,4 390 402
251,Sem. 35,26-10-2020,-1548,46 930,1859,890 574,3359,810 995,48,34 197,NaN,5615,1070,NaN,16 891,4 407 293
252,Semana,Fecha,Var.,Acum.,Nuevos,Acum.,Nuevos,Acum.,Nuevos,Acum.,NaN,Hosp.,UCI,NaN,Nuevos,Acum.
253,Semana,Fecha,Activos,Activos,Confirmados,Confirmados,Recuperados,Recuperados,Muertes,Muertes,NaN,Severos,Severos,NaN,PCR+PR,PCR+PR
254,Semana,Fecha,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,Casos,NaN,Pruebas,Pruebas